config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'
  get 'say/goodbye'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # get "/articles/new", to: "articles#new"
  # get "/articles/:id", to: "articles#show"
  # patch "/articles/:id", to: "articles#update"
  # delete "/articles/:id", to: "articles#destroy"

  # get "/articles/:id/edit", to: "articles#edit"
  # post "/articles", to: "articles#create"

  # get "/articles", to: "articles#index"
  # Defines the root path route ("/")

  resources :articles do
    resources :comments
  end
  
  root "articles#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments 

    validates :title, presence: true
    validates :body, presence: true, length: {minimum: 10}

    VALID_STATUSES = ['public', 'private', 'archived']

    validates :status, inclusion: { in: VALID_STATUSES }

    def archived?
        status == 'archived'
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  VALID_STATUSES = ['public', 'private', 'archived']

  validates :status, inclusion: { in: VALID_STATUSES }

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :set_article, except: [:index, :new, :create]
  before_action :set_article, only: %i[ show edit update destroy ]

  def index
    @articles = Article.all
  end

  def show
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end  

  # create but does not save it
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private

  # use strong params
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end

  def set_article
    @article = Article.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path  
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        # we send the user back to the original article
        redirect_to article_path(@article)
    end

    private
        def comment_params
            # We also have to permit the :status key as part of the strong parameter
            params.require(:comment).permit(:commenter, :body, :status)        
        end
        
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @files = Dir.glob('*')
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h2>Edit Article</h2>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Blog Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %>
        (<span><%= article.status %><span>)
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "add new Article", new_article_path %>

app/views/articles/new.html.erb
<h2>New article</h2>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<article>
    <h2><%= @article.title %></h2>
    <p><%= @article.body %></p>
</article>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li>
    <%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
  </li>
</ul>q

<h2>Comments:</h2>
<%# As the render method iterates over the @article.comments collection %>
<%# <% @article.comments.each do |comment| ... %>
<ul>
  <%= render @article.comments %>
</ul>


<h2>Add a comment</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
    <li>
    <div>
        <strong>Commenter:</strong>
        <p><%= comment.commenter %></p>
    </div>

    <div>
        <strong>Comment:</strong>
        <p><%= comment.body %></p>
    </div>
    </li>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div>
      <% if user_signed_in? %>
        <% link_to "Profile", edit_user_registration_path %>
        <% button_to "Log out", destroy_user_session_path, method: :delete %>
      <% else %>
        <% link_to "Login", new_user_session_path  %>
        <% link_to "Sign up", new_user_registration_path  %>
      <% end %>
    </div> 

    <%= yield %>

  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>Find me in app/views/say/goodbye.html.erb</p>

<h1>Goodbye!</h1>
<p>
  It was nice having you here.
</p>

<p>
    Say
    <%= link_to "Hello", say_hello_path %>! 
</p>

app/views/say/hello.html.erb
<h1>Say#hello</h1>
<p>Find me in app/views/say/hello.html.erb</p>

<div>
    <p>
        It is now <%= @time %> 
    </p>
    Time in one hour: <%= 1.hour.from_now.localtime %>
    <p><%= "cow" + "boy" %></p>
    <p>add <%= 1+2 %></p>
</div>

<div>
    Files
    </br>
    A call to the following Ruby method returns a list of all the files in the current directory:
    <ul>
    <% @files.each do |file| %> 
       <li> 
            file name is: <%= file %> 
        </li>
    <% end %>
    </ul>
</div>


<p>
    Time to say
    <%= link_to "Goodbye", say_goodbye_path %>! 
</p>